### ISSUE TITLE
Mac Mount documentation

### ISSUE THREAD

**Issue by dwalkes** [libyal/libluksde#2]
Thanks for sharing this project!

I was able to build libluksde from source and read a LUKS volume on Mac today with one small addition to the wiki instructions - see the commit [here](https://github.com/dwalkes/Libluksde-Wiki/commit/d640925d4143b2e78320951c44b91304f72250ba) for details.

**Comment by joachimmetz** [comment]
thx for the feedback, the docs are generated by https://github.com/libyal/libyal/blob/master/scripts/wiki-generate.py I'll add the changes to the template

**Comment by joachimmetz** [comment]
Wiki updated
