### ISSUE TITLE
I think it will be && instead of ||

### ISSUE THREAD

**Issue by pPanda-beta** [libyal/libluksde#6]
At this condition, 
https://github.com/libyal/libluksde/blob/8ef2855953e79a211cb98ca96b9ef8c5b64176f3/luksdetools/info_handle.c#L397-L399

The plan is to check whether the string length is whether 32, 64 or 128. 

e.g. if `string_length = 33` then `( string_length != 32 ) && ( string_length != 64 ) && ( string_length != 128 ) => true`
and `string_length = 64` then `( string_length != 32 ) && ( string_length != 64 ) && ( string_length != 128 ) => false`

**Comment by joachimmetz** [comment]
thanks for flagging, I'll have a look when time permits

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libluksde/commit/24fae0c7670dd31ea836d635f65766ba646151de
